### ISSUE TITLE
Chapter Loop Button gets paw-ified

### ISSUE THREAD

**Issue by SteffoSpieler** [FulytheFox/paw-up-userstyle#3]
Without paw-up:
![grafik](https://user-images.githubusercontent.com/41108856/178948147-bd689199-b006-4e30-b02c-7e0feebd521d.png)

With paw-up:
![grafik](https://user-images.githubusercontent.com/41108856/178948213-690c5909-665b-4113-895a-5a8eba1a8cee.png)

**Comment by FulytheFox** [comment]
Thank you for reporting this bug.
I pushed an update that should fix it. You can go to the [Paw Up!](https://userstyles.org/styles/169802) userstyle.org page and press the Update Style button to update the userstyle.
