### ISSUE TITLE
Fix for youtube redesign

### ISSUE THREAD

**Issue by slopslug** [FulytheFox/paw-up-userstyle#4]
Currently doesn't work with youtube's latest redesign. CSS classes probably got shuffled around

**Comment by FulytheFox** [comment]
Thanks for the bug report! I will take a closer look at Youtube's redesign and push an update in the next few days.

**Comment by FulytheFox** [comment]
I pushed an update that now supports the new design. You can update the userstyle in a few minutes on [userstyles.org](https://userstyles.org/styles/169802).
