### ISSUE TITLE
Paws up! icon not working :(

### ISSUE THREAD

**Issue by Pastelliouspink** [FulytheFox/paw-up-userstyle#9]
recently the paws icon was working fine and now some time after its completely gone. when i reset it to try again it does not work at all, any help? thank you :( its on userstyle...

**Comment by FulytheFox** [comment]
Hey, thanks for letting me know!

It seems that youtube has changed its code for the like/dislike buttons on videos. I'll take a closer look about this in the next few days and push an update.

Do you only have this problem with videos or also with comments, community posts and shorts?

**Comment by Pastelliouspink** [comment]
no problem! the feature is so cute!! as far as ive seen the paws just don't activate at all. however, everything else is fine :) nothing has been affected, just the fact the paws don't show up anymore when activating it.

**Comment by FulytheFox** [comment]
I pushed an update that should fix the issue. You can update the userstyle on [userstyles.org](https://userstyles.org/styles/169802) or download the update manually. If it still doesn't work, just reopen the issue!
